# Generated by Django 4.2.1 on 2023-07-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0006_room_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='room',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
