# Generated by Django 4.2.1 on 2023-07-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0007_remove_review_author_remove_review_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='preview',
        ),
    ]
